home:
    pattern: /
    defaults: { _controller: MakeYourTeamBundle:Public:index }

annonce_page:
    pattern: /page/{page}
    defaults: { _controller: MakeYourTeamBundle:Annonce:page }
    requirements:
        page: \d

annonce_article:
    pattern: /article
    defaults: { _controller: MakeYourTeamBundle:Annonce:article }

annonce_add:
    pattern: /annonce/add
    defaults: { _controller: MakeYourTeamBundle:Annonce:add }